### ISSUE TITLE
Problem compiling demo on ArchLinux

### ISSUE THREAD

**Issue by miko** [vinniefalco/LuaBridgeDemo#1]
Trying to compile LuaBridgeDemo pulled out of github:

$ make
Compiling juce_core_amalgam.cpp
Compiling juce_data_structures_amalgam.cpp
Compiling juce_events_amalgam.cpp
Compiling juce_graphics_amalgam.cpp
Compiling juce_gui_basics_amalgam.cpp
Compiling LuaLibrary.cpp
Compiling Main.cpp
In file included from /usr/lib/gcc/i686-pc-linux-gnu/4.7.0/../../../../include/c++/4.7.0/ext/hash_map:61:0,
                 from ../../../LuaBridge/RefCountedPtr.h:39,
                 from ../../Source/Main.cpp:33:
/usr/lib/gcc/i686-pc-linux-gnu/4.7.0/../../../../include/c++/4.7.0/backward/backward_warning.h:33:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1426:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1012:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1439:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1025:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1452:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1038:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1465:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1051:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1478:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1064:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1491:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1077:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1505:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1091:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1519:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6, P7), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1105:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6, P7), D>’
In file included from ../../Source/Main.cpp:32:0:
../../../LuaBridge/LuaBridge.h:1534:8: error: redefinition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6, P7, P8), D>’
../../../LuaBridge/LuaBridge.h:1120:8: error: previous definition of ‘struct luabridge::FuncTraits<R (*)(P1, P2, P3, P4, P5, P6, P7, P8), D>’
../../../LuaBridge/LuaBridge.h:1551:8: error: redefinition of ‘struct luabridge::FuncTraits<R (T::*)(), D>’
../../../LuaBridge/LuaBridge.h:1137:8: error: previous definition of ‘struct luabridge::FuncTraits<R (T::*)(), D>’
...
and so on.
Using Lua 5.1.5, gcc 4.7.0

**Comment by vinniefalco** [comment]
GCC doesn't distinguish functions based on their throw-specification so I removed the #define THROWSPEC for GCC targets. This is fixed in all branches of the demo, and hotfixed in LuaBridge. Thanks for bringing this up!

**Comment by miko** [comment]
Compiles now. Thanks!
